package ENUM;

public enum Genero {
    ACCION, COMEDIA, AVENTURA, FANTASIA, TERROR, BELICO, ROMANTICO, COMEDIA_ROMANTICA,
    AVENTURA_FANTASIA, ACCION_AVENTURA, FANTASIA_DRAMA_ACCION_AVENTURA_TERROR,
    ACCION_AVENTURA_COMEDIA_ARTESMARCIALES_FANTASIA, ACCION_AVENTURA_COMEDIA_FANTASIA_TRAGEDIA,
    ACCION_AVENTURA_COMEDIA_FANTASIA;
}
